server:
  port: 8110

spring:
  datasource:
    username: sa
    password:
    url: jdbc:h2:./shiro;AUTO_SERVER=TRUE
  jpa:
    database: h2
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        "[format_sql]": true
